[package]
name = "rust-fraud-detector"
version = "0.1.0"
edition = "2021"

[dependencies]
# The asynchronous runtime
tokio = { version = "1", features = ["full"] }

# The web framework
axum = "0.6"

# For serializing and deserializing JSON data
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

# For logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# For handling dates and times
chrono = { version = "0.4", features = ["serde"] }
